server:
  8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: linksdb
      username: kh
      password: 1234
      uri: mongodb://localhost:27017/linksdb

  security:
    authorization: 'enabled'
